### ISSUE TITLE
Product description on NPM page is missing a space in the brand name

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp#1]
Minor thing...
"JavaScript/TypeScript SDK to create CarbonLDP's Applications"
Should be:
"JavaScript/TypeScript SDK to create Carbon LDP applications"

**Comment by jgf20** [comment]
This issue corresponds to carbonldp-js-sdk the npm descriptions are taken from the README.md and the package.json files in that project

Moved to https://github.com/CarbonLDP/carbonldp-js-sdk/issues/118
