### ISSUE TITLE
Change "carbonldp-typescript-boilerplate" default port

### ISSUE THREAD

**Issue by andynice** [CarbonLDP/carbonldp#12]
As a suggestion, while using this boilerplate, the configured port is 8000, but it is the same as the one used for workbench

<img width="467" alt="screen shot 2018-01-21 at 4 52 27 pm" src="https://user-images.githubusercontent.com/1441124/35199953-7fd65ece-fecb-11e7-9fac-4e4b2dea22a8.png">
<img width="543" alt="screen shot 2018-01-21 at 4 52 55 pm" src="https://user-images.githubusercontent.com/1441124/35199960-8c941174-fecb-11e7-8d41-a22a2e9ef20b.png">

So it opens by default workbench

I think it would be better if they're different, from the beginners perspective.

**Comment by MiguelAraCo** [comment]
Closing this issue since the boilerplate is no longer maintained.
