### ISSUE TITLE
In the web Site, the License link is not working

### ISSUE THREAD

**Issue by andynice** [CarbonLDP/carbonldp#13]
This link is included in the quick start guide
https://carbonldp.com/license
<img width="798" alt="screen shot 2018-10-06 at 8 59 34 pm" src="https://user-images.githubusercontent.com/1441124/46577332-d0d45600-c9aa-11e8-9aec-e8a9cf7e9d68.png">

**Comment by mhernandeza** [comment]
This issue is pertinent to the website. I have moved this issue to the CarbonLDP/carbonldp-website project. You can track its progress here: CarbonLDP/carbonldp-website#414.
