### ISSUE TITLE
In the website, a screenshot shows different port

### ISSUE THREAD

**Issue by andynice** [CarbonLDP/carbonldp#14]
In the quick start guide, the screenshot in the section "Running the Carbon LDP workbench" shows the port 8080, when the instructions indicate the "localhost:8000"

**Comment by mhernandeza** [comment]
This issue is pertinent to the website. I have moved this issue to the CarbonLDP/carbonldp-website project. You can track its progress here: CarbonLDP/carbonldp-website#415.
