### ISSUE TITLE
Access Control Entries stay in ACL with no subject property

### ISSUE THREAD

**Issue by iamenrique** [CarbonLDP/carbonldp#4]
When a permission is added in a document's ACL, it must include a `subject` property pointing to the agent or role which we are granting or denying access. This action creates (or modifies) an ACE. But when the role is deleted, it also removes the `subject` property from all the ACE's that point to it leaving the ACE with no subject. I also noticed that an error is produced when I try to obtain an ACL in that situation (read lenght property from undefined)

**Comment by MiguelAraCo** [comment]
This is a bug of the platform. I moved the issue to the CarbonLDP/public-carbonldp-platform repository. You can track its process here: CarbonLDP/public-carbonldp-platform#2
