### ISSUE TITLE
Prepare Carbon LDP Public for testing with Linked Data Notifications

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp#6]
Sarven Capadisli would like to run some of his tests for Linked Data Notifications against Carbon. I'd like for us to work with him as it will be a beneficial exercise for us. As a first step, we need to update the version on our internal public Carbon server and then we can contact Sarven and discuss next steps.

For the record, we can DM Sarven on Twitter at: https://twitter.com/csarven

LDN TestSuite
https://github.com/csarven/ldn-tests

Last Twitter Conversation:

Cody

Spoke to my lead dev today. We have a Carbon server on cloud, but is not updated to latest version. He will be working on that - then we'll get back to you. Holiday madness has got us very busy this week.
One thing we noticed is that your testsuite does not seem to support authentication, so we'd have to setup a Carbon app with public access, I guess.

Sarven Capadisli:

No worries, and thanks for pushing this. I can have a look at it as part of our tests probably next week

Or - alternatively - you may wish to have support for authentication in the testsuite.

We have implemented a security model. So, by default, everything's private unless you add ACLs for public access.

Sarven Capadisli

Yes, that'd be great. First trying to get the must haves put off the way

Cody Burleson
But, for the short-term, we could make a public app.

Sarven Capadisli
I won't do anything heavy there btw. Feel free to chat the container at your own discretion

Err.. on mobile. I meant clear not chat

Cody Burleson

(In Carbon, "Apps" are like data-spaces where all the resources for your app go. One Carbon server can have multiple "apps". Each with their own security and such.)
So, we could create a public app for you, I suppose.

We'll get back to you when it's set up. And we'll probably need to follow up with some kind of brief overview.

**Comment by MiguelAraCo** [comment]
Our current dev platform and workbench have been updated. Credentials and a public application were created and shared through email.
