### ISSUE TITLE
Import backup cannot be completed

### ISSUE THREAD

**Issue by vgragon** [CarbonLDP/carbonldp#8]
When trying to migrate from one carbon app to another (with existing data), the process did not complete successfully.

Followed steps were:
1. Generate backup from origin app
2. Download backup
3. Upload backup in destination app
4. Import backup

_The backup will be passed through another application._

**Comment by MiguelAraCo** [comment]
What do you mean it didn't complete successfully? Did you get any errors?

**Comment by vgragon** [comment]
Hi Miguel. I got "Unknown" error, the front-end showed the process failed and it does not seem to have finished in the back-end either, since my destination app remains the same.

@NestorEstrada has been helping me with the issue, as well as @alvaro9210. I hope they could give you more detailed information.

**Comment by MiguelAraCo** [comment]
This issue corresponds to an older version and it is probably no longer relevant.
